apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend
    version: blue   # 🔄 This will be patched by Jenkins to 'green' during rollout
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
