apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend       # ✅ must match Deployment
    version: blue       # ✅ include version if pod has it
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80    # ✅ Nginx container port
