apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: ecommerce-frontend
spec:
  selector:
    app: ecommerce-frontend
  ports:
    - protocol: TCP
      port: 80          # Exposes port 80 outside the cluster
      targetPort: 3001  # Port on the frontend container
  type: LoadBalancer     # Or NodePort if you're using Minikube/EKS with external LB
